// Auto-generated from Word documents
export const journals = [
  {
    "id": "blog-1",
    "slug": "what-a-morning-walk-taught-me-about-colour",
    "title": "What a Morning Walk Taught Me About Colour",
    "date": "July 2026",
    "coverImage": "/Blogs/Blog 1/30610472460962513.jfif",
    "summary": "What a Morning Walk Taught Me About ColourThat No Art Class Ever DidThe most powerful colour education available to any artist costs nothing and is ou...",
    "contentHtml": "<p><strong>What a Morning Walk Taught Me About Colour</strong></p><p><strong>That No Art Class Ever Did</strong></p><p>The most powerful colour education available to any artist costs nothing and is outside your front door right now.</p><p>I walk the same route most mornings near my home. I have walked it in every season. In sun and rain and the particular grey light of a German November.</p><p>And every single time the colour is different.</p><p><strong>What books teach vs what walks teach</strong> </p><p>Books teach you colour theory. Walks teach you colour reality. A leaf is not one green. It contains ochre at the base, blue in the shadow, yellow where the light hits it directly. That complexity is what makes botanical painting extraordinary — and you can only see it by looking closely at the actual thing.</p><p><strong>How to look differently</strong> </p><p>Slow down to half your usual pace. Look for the unexpected colour first — the purple in what should be a green leaf, the warmth at the base of a white flower. These are the colours nobody sees and that make paintings unforgettable when they appear.</p><p><strong>What to bring</strong> </p><p>Your phone for close-up photographs. A small notebook for colour notes made on the spot. Nothing else required.</p><p><strong>The three colours I discovered on walks that changed my palette</strong> </p><p>The blue in a green shadow. The warmth at the base of every stem. The fact that white flowers are never actually white.</p><p>Go outside today. Find one thing that is a different colour than you expected.</p><p>That is where your next painting begins</p>"
  },
  {
    "id": "blog-2",
    "slug": "why-i-paint-at-my-kitchen-table",
    "title": "Why I Paint at My Kitchen Table",
    "date": "July 2026",
    "coverImage": "/Blogs/Blog 2/Artists sketchbook with botanical drawings, watercolor palette, and brushes on wooden table.jfif",
    "summary": "Why I Paint at My Kitchen TableAnd Why You Should TooYou do not need a studio. You need a surface, a window and the decision to begin.I paint at a kit...",
    "contentHtml": "<p><strong>Why I Paint at My Kitchen Table</strong></p><p><strong>And Why You Should Too</strong></p><p>You do not need a studio. You need a surface, a window and the decision to begin.</p><p>I paint at a kitchen table in Frankfurt. I clear it before dinner. I set it up again the next morning. Every painting I am proud of was made on that table.</p><p>The studio myth is the most expensive creative lie there is. It convinces people to wait — for more space, a better setup, the right conditions — while the paintings they could be making sit unmade inside them.</p><p><strong>What you actually need</strong> </p><p>A tray that holds your supplies. Two water jars. A good window. Two minutes to set up. Two minutes to clear away.</p><p>That is it. That is the entire studio.</p><p><strong>The secret the myth hides</strong> </p><p>The artists who improve are not the ones with the best spaces. They are the ones who show up most consistently. A kitchen table you paint at every day is worth more than a dedicated studio you visit twice a month.</p><p><strong>The one thing that changes everything</strong> </p><p>Make the setup take less than two minutes. Remove every possible reason to delay. The moment the friction disappears the practice begins.</p><p>Your kitchen table is already a studio. You just have to sit down at it.</p><p><em>Ready to set up your space and finally begin? </em></p><p><em>My free guide — Your Creative Space — has everything you need</em></p>"
  },
  {
    "id": "blog-3",
    "slug": "five-things-i-wish-i-had-known-before-i-started-painting",
    "title": "Five Things I Wish I Had Known Before I Started Painting",
    "date": "July 2026",
    "coverImage": "/Blogs/Blog 3/Pic 1.jfif",
    "summary": "Five Things I Wish I Had Known Before I Started PaintingNobody tells you these things. So I will.Your first paintings are supposed to be bad Not might...",
    "contentHtml": "<p><strong>Five Things I Wish I Had Known Before I Started Painting</strong></p><p>Nobody tells you these things. So I will.</p><p><strong>Your first paintings are supposed to be bad</strong> </p><p>Not might be bad. Are going to be bad. Consistently. Across many sessions and many sheets of paper. This is not evidence that you are not an artist. It is the definition of being a beginner. The only way across the gap between what you can imagine and what you can produce is through it.</p><p><strong> The paper matters more than the paint</strong></p><p> Cheap paper buckles, resists and muddies everything. Good 300gsm cold-press watercolour paper makes every technique easier. Buy less paint if you have to. Never compromise on the paper.</p><p><strong>More water than you think</strong> </p><p>Watercolour's luminosity comes from water, not pigment. Whatever amount of water you think you need — add more. Work light to dark. Always.</p><p><strong>Let it dry</strong></p><p> Adding wet paint to a damp layer creates mud. Every time. Use a hairdryer if you are impatient. But wait. The willingness to let it dry is one of the clearest signs of a developing artist.</p><p><strong>Stop comparing</strong> </p><p>You are looking at the best work of someone who has been painting for years, carefully selected and posted on a confident day. You are not seeing their first paintings. Compare yourself only to yourself six months ago. That gap is the only measure that matters.</p><p>Starting is hard. The middle is hard. All of it is the practice.</p><p>I am still in the middle of it. Every day. At my kitchen table.</p><p>And it is the most honest thing I do. </p>"
  },
  {
    "id": "blog-4",
    "slug": "why-negative-space-is-the-most-powerful-tool",
    "title": "Why Negative Space Is the Most Powerful Tool",
    "date": "July 2026",
    "coverImage": "",
    "summary": "Why Negative Space Is the Most Powerful ToolYou Are Probably Not UsingMost beginner painters fill the page.It is a completely understandable impulse....",
    "contentHtml": "<p><strong>Why Negative Space Is the Most Powerful Tool</strong></p><p><strong>You Are Probably Not Using</strong></p><p>Most beginner painters fill the page.</p><p>It is a completely understandable impulse. You have a beautiful sheet of paper and a beautiful subject and you want to use every inch of both. More paint feels like more effort. More effort feels like more value.</p><p>But the paintings that stop people — the ones they cannot look away from — are almost never the fullest ones.</p><p><strong>What negative space actually is</strong> </p><p>The unpainted areas of a painting. The white paper that remains. The air around a botanical subject. The silence between marks.</p><p>It is not emptiness. It is a colour. It is a decision. It is often the most important thing on the page.</p><p><strong>What it does to the viewer</strong> </p><p>It gives the eye somewhere to rest. It makes the painted elements appear more considered and more valuable. It creates the breathing room that makes a painting feel calm rather than crowded.</p><p>A painting with generous negative space asks the viewer to slow down. And a viewer who slows down in front of your work is a viewer who feels something.</p><p><strong>The rule I follow</strong> </p><p>Before I begin any painting I decide how much of the paper I want to remain untouched at the end. I give it a number. At least forty percent. Then I treat that commitment as seriously as any other compositional decision.</p><p><strong>Try this today</strong> </p><p>Paint your usual subject occupying only one third of the page. Leave the rest completely untouched. It will feel wrong immediately.</p><p>Live with it for a day. Look at it again tomorrow.</p><p>Notice what happened to the painting overnight.</p><p>Nothing changed. And everything did. </p>"
  },
  {
    "id": "blog-5",
    "slug": "the-colour-that-changed-everything",
    "title": "The Colour That Changed Everything",
    "date": "July 2026",
    "coverImage": "/Blogs/Blog 5/394979829802099752.jfif",
    "summary": "The Colour That Changed EverythingHow One Tube of Paint Became My SignatureI remember the first time I used Prussian blue.I had been painting for abou...",
    "contentHtml": "<p><strong>The Colour That Changed Everything</strong></p><p><strong>How One Tube of Paint Became My Signature</strong></p><p>I remember the first time I used Prussian blue.</p><p>I had been painting for about four months. My palette was a confused collection of every colour that had looked interesting in the shop. My paintings were technically reasonable and completely without identity.</p><p>Then I picked up a tube of Prussian blue because something about it felt right in a way I could not explain. I laid down a wash. I watched it dry. I have used it in every single painting I have made since.</p><p><strong>What a signature colour actually does</strong></p><p> It creates continuity across your work. A viewer who sees five of your paintings together should be able to feel the thread connecting them even before they see your name. Colour is the strongest thread available.</p><p><strong>How to find yours</strong> </p><p>Stop buying colours that look interesting and start noticing which colours you actually reach for. Open your palette right now. Which colours have almost run out. Which have barely been touched. Your signature colour has been there all along. You just have not named it yet.</p><p><strong>Why limitation is freedom</strong> </p><p>The painters whose work I find most compelling are almost never the ones with the most colours. They are the ones who know their five colours with extraordinary intimacy. Who know exactly what happens when this blue meets that green at this particular water ratio on this paper.</p><p>That knowledge only comes from constraint. Choose less. Go deeper.</p><p><strong>What Prussian blue taught me</strong> </p><p>That a signature is not something you design. It is something you discover by paying attention to what you keep returning to.</p><p>Your colour is already showing you who you are.</p><p>Pay attention. </p><p><em>Download my free guide — Finding your color story — to gain more insights</em></p>"
  },
  {
    "id": "blog-6",
    "slug": "why-being-self-taught-is-a-strength",
    "title": "Why Being Self-Taught Is a Strength",
    "date": "July 2026",
    "coverImage": "/Blogs/Blog 6/399413060726829851.jfif",
    "summary": "Why Being Self-Taught Is a StrengthNot a Gap You Need to FillEvery time someone asks where I studied I feel a small familiar flinch.Nowhere. I studied...",
    "contentHtml": "<p><strong>Why Being Self-Taught Is a Strength</strong></p><p><strong>Not a Gap You Need to Fill</strong></p><p>Every time someone asks where I studied I feel a small familiar flinch.</p><p>Nowhere. I studied nowhere. I taught myself at a kitchen table in Frankfurt with a beginner's brush set and a very patient sheet of paper.</p><p>For a long time I apologised for that. I no longer do.</p><p><strong>What formal training gives you</strong> </p><p>Structure. Vocabulary. Foundational technique. Connections. These are real and valuable things.</p><p><strong>What it takes away</strong> </p><p>The permission to be wrong. The freedom to develop strange habits that turn out to be your style. The blissful ignorance of rules you might have followed too carefully if you had known them.</p><p><strong>What self-teaching forces you to develop</strong> </p><p>Resourcefulness. Genuine curiosity. The habit of looking closely at work you admire and asking not just what it is but how it was made and why it works. These are skills that no classroom produces. They can only come from necessity.</p><p><strong>The thing nobody says out loud</strong> </p><p>Some of the most distinctive artistic voices working today are self-taught. Not despite their lack of formal training. Because of it. Their work does not look like it came from a curriculum. It looks like it came from a specific person.</p><p>That specificity is the thing that makes art worth looking at.</p><p><strong>What this means for you</strong> </p><p>If you have been waiting to begin until you have taken a class or found a teacher or felt qualified enough — stop waiting. Begin now with what you have and what you know.</p><p>The practice is the education. It has always been</p>"
  }
];
